# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml   

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship(8921afe2-c36e-462e-9106-176a887e8cb0)'
    appType: 'webApp'
    appName: 'LucaApp'
    deployToSlotOrASE: true
    resourceGroupName: 'RgStage'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'lucawebapp'
    publishLocation: 'pipeline'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
